[tool.poetry]
name = "ppz"
version = "0.1.0"
description = ""
authors = ["Andreichuk Volodymyr <v.andreichuk@firstsport.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
